version: 1.0.{build}
image: Visual Studio 2017
build_script:
- ps: >-
    # CLI tooling still not first class citizen https://github.com/appveyor/ci/issues/1404

    cd ./src

    dotnet build
test:
  assemblies:
    only:
    - Adaptive.Agrona.Tests.dll
    - Adaptive.Aeron.Tests.dll
after_test:
- ps: >-
    dotnet test -f netcoreapp2.0 ./Adaptive.Agrona.Tests/Adaptive.Agrona.Tests.csproj --logger "trx;LogFileName=AgronaResults.trx"

    dotnet test -f netcoreapp2.0 ./Adaptive.Aeron.Tests/Adaptive.Aeron.Tests.csproj --logger "trx;LogFileName=AeronResults.trx"


    # upload results to AppVeyor

    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path ./Adaptive.Agrona.Tests/TestResults/AgronaResults.trx))

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path ./Adaptive.Aeron.Tests/TestResults/AeronResults.trx))